model:
  type: oci  # Options: oci, gemini, ollama
  #type: gemini  # Options: oci, gemini, ollama
  #type: ollama  # Options: oci, gemini, ollama
  
  # OCI model parameters
  oci_params:
    #model_name: "cohere.command-r-plus-08-2024"
    #model_name: "cohere.command-r-08-2024"
    #model_name: "meta.llama-3.1-405b-instruct"
    #model_name: "cohere.command-a-03-2025"
    #model_name: "meta.llama-3.3-70b-instruct"
    #model_name: "meta.llama-4-maverick-17b-128e-instruct-fp8"
    model_name: "meta.llama-4-scout-17b-16e-instruct"
    endpoint: "https://inference.generativeai.us-chicago-1.oci.oraclecloud.com"
    compartment_id: "ocid1.compartment.oc1..aaaaaaaaxj6fuodcmai6n6z5yyqif6a36ewfmmovn42red37ml3wxlehjmga"
    model_kwargs:
      temperature: 0.7
      max_tokens: 500
    auth_profile: "INNO-SANDBOX"
  
  # Gemini model parameters
  gemini_params:
    model_name: "gemini-2.0-flash"
    temperature: 0.7
    max_tokens: 500
    api_key: ${GEMINI_PERSONAL}

  # Ollama model parameters
  ollama_params:
    model_name: "llama3-groq-tool-use"
    #model_name: "deepseek-r1"
    #model_name: "phi4-mini"
    #model_name: "mistral"
    url: "https://macmini.industrylab.uk/ollama/"
    temperature: 0.7
    api_key: ${OLLAMA_AUTHKEY}

# Custom system prompt (optional)
lookup_prompt: >
    You are a oracle of all knowledge and can explain  complex questions in an easy to understand manner. 
    Give a short summary explanation of 3-4 sentences max.
explain_prompt: >
    You are a professional developer. You explain complex commands or code snippets in an easy to understand but succinct way. 
    Give a short summary explanation of 3-4 sentences max.
help_prompt: >
    You are a apple commandline developer. you know a wide variety of linux like commands that can be executed in the terminal. 
    Give a 2-3 options for command baed on the decription below. each command option is one line with command and parameters explained"
cmd_prompt: >
    you are a command line expert who only responds in valid json. generate a valid macos command line for zsh to accomplish the given task.
    Give alternatives if possible. Respond with valid json only with format { "1":"response1","2":"response2"}. just one line response for each alternative.
    ensure your response is a valid json no errorss. try to give at least 3 alternatives when possible.
    Here are a few examples of the response i am looking for: 
    task: edit  file1.txt in  dir abc
    response: {"1":"vi abc/file.txt", "2":"nano abc/file.txt"}
    task: find  file1.txt in  dir abc
    response: {"1":"find abc -name file1.txt -type f"}
    task:  print a file
    response: {"1":"cat file", "2":"head file", "3":"tail file"}
proof_expand_prompt: >
     you are a expert template filler. I will provide you with the tag from teh teamplate. You will only provide a short response just for that tag 
     your responde will repalce that tag in the template.  dont include any other text.
     if generating code don not generate any extra text, backticks or test examples as your generated code is being added to the existing code as is.
     make sure you output compiles error free. 

proof_clean_prompt: >
      you are a professional copy editor, proficient in grammer & spellings,
      keep the original voice, tone & content. correct any typo & grammer 
      your response will be used to replace original text in an professional communication. thus do not include any aditional text. 
      you may be given markdown, html or plain text. output in same format. 
      do not attempt to execute any comamnds. just copy edit for typos & grammer  
